jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
        --channel=1 --sdk_root=${ANDROID_SDK_ROOT} | grep -v = || true
    - continue-on-error: true
      name: Get version code
      run: echo APPVEYOR_BUILD_NUMBER=$(expr $GITHUB_RUN_NUMBER + 4999) >> $GITHUB_ENV
    - continue-on-error: true
      name: Build with Gradle
      run: bash ./gradlew zipRelease zipDebug
    - continue-on-error: true
      if: success()
      name: Prepare artifact
      run: unzip edxp-core/release/EdXposed-v*-release.zip -d EdXposed-release; unzip
        edxp-core/release/EdXposed-v*-debug.zip -d EdXposed-debug;
    - continue-on-error: true
      name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: EdXposed-release
        path: ./EdXposed-release/*
    - continue-on-error: true
      name: Upload debug
      uses: actions/upload-artifact@v2
      with:
        name: EdXposed-debug
        path: ./EdXposed-debug/*
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
